### ISSUE TITLE
Add A Readme.md with basic info

### ISSUE THREAD

**Issue by ramonGonzEdu** [SpaceTradersAPI/awesome-spacetraders#1]
Add a basic Readme file with a title and info about this repo

**Comment by JayWalker512** [comment]
I'll make a PR with this in the next couple days unless someone beats me to it.

**Comment by jadlers** [comment]
It's in the process, I've just personally been busy with managing other parts of the project. I'll work on it tomorrow unless someone creates a PR before me!

**Comment by jadlers** [comment]
Just added the initial version of the readme
